version: '3.1'

services:
  springboot:
    image: chintamkavitha/spring-boot-mongo:${buildNumber}
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=kavithadb
    - MONGO_DB_PASSWORD=kavithadb@123
    ports:
      - 9080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappbridge

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=kavithadb 
    - MONGO_INITDB_ROOT_PASSWORD=kavithadb@123
    volumes:
      - mongovol:/data/db
    restart: always
    networks:
    - springappbridge
    
volumes:
  mongovol:
    driver: local
    
networks:
  springappbridge:
    driver: bridge
